Desktop/todolist/tasks/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'tasks'
urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name = 'detail'),
    path('create',views.CreateTask.as_view(),name = 'add_task'),
    path('',views.IndexView.as_view(),name='homepage'),
    path('task/<int:pk>/',views.UpdateTask.as_view(),name = 'update_task'),
    path('task/<int:pk>/delete/',views.DeleteTask.as_view(),name = 'delete_task'),
    ]

Desktop/todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lists/',include('tasks.urls')),
]

Desktop/todolist/tasks/models.py
from django.db import models
from django.urls import reverse,reverse_lazy
# Create your models here.
class Tasks(models.Model):
    TaskName = models.CharField(max_length = 100)
    Description = models.CharField(max_length = 400)
    DueDate = models.DateField()
    priority = models.IntegerField()

    def __str__(self):
        return self.TaskName
    def get_absolute_url(self):
        return reverse('tasks:detail',kwargs={'pk':self.pk})

Desktop/todolist/tasks/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from .models import Tasks
from django.urls import reverse,reverse_lazy
# Create your views here.
#def home(request):
#    return render(request,'tasks/home.html')
class IndexView(generic.ListView):
    template_name = 'tasks/home.html'
    context_object_name = 'all_tasks'
    def get_queryset(self):
        return Tasks.objects.all()
class DetailView(generic.DetailView):
    template_name = 'tasks/detail.html'
    model = Tasks
    context_object_name = 'task'
class CreateTask(generic.CreateView):
    template_name = 'tasks/forms_template.html'
    model = Tasks
    fields = ['TaskName','Description','DueDate','priority']
class UpdateTask(generic.UpdateView):
    template_name = 'tasks/forms_template.html'
    model = Tasks
    fields = ['TaskName','Description','DueDate','priority']
class DeleteTask(generic.DeleteView):
    model = Tasks
    success_url = reverse_lazy('tasks:homepage')

Desktop/todolist/tasks/templates/tasks/detail.html
<html>
<a href = "{% url 'tasks:homepage'%}">Home</a>
<h1>{{task}}</h1>
<h2>{{task.Description}}</h2>
<h2>Due date {{task.DueDate}}</h2>
<br>
<ul>
<li>
<a href = "{% url 'tasks:update_task' task.id %}">Edit Task</a></li>
<li>
<a href = "{% url 'tasks:delete_task' task.id %}">Delete Task</a></li>
</ul>
</html>

Desktop/todolist/tasks/templates/tasks/forms_template.html
<html>
<h1>Enter Details of The Task</h1>
<form method = "post">
{% csrf_token %}
{{form.as_p}}
<input type = "submit" value = "add">
</form>
<html>

Desktop/todolist/tasks/templates/tasks/home.html
<html>
<h1>Welcome To The To-do-List</h1>
<a href = "{% url 'tasks:add_task' %}">Add a task here</a>
<h2>List of Tasks</h2>
<ul>
{% for task in all_tasks %}
<li><a href = " {% url 'tasks:detail' task.id %}">{{task}}</a></li>
{% endfor %}
</ul>
</html>

Desktop/todolist/tasks/templates/tasks/tasks_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>